# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-12 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_articles", "0009_number_min_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="revision_id",
        ),
    ]
