# Generated by Django 3.2.25 on 2024-05-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("import_wordpress", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="import_wordpress.author",
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="link",
            field=models.CharField(max_length=512, verbose_name="link"),
        ),
        migrations.AlterField(
            model_name="item",
            name="pub_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="publication date"),
        ),
    ]
